# Generated by Django 5.2.7 on 2025-11-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ci",
            fields=[
                (
                    "value",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="编号",
                    ),
                ),
                ("rhythmic", models.CharField(max_length=20, verbose_name="词牌名")),
                ("author", models.CharField(max_length=20, verbose_name="作者")),
                ("content", models.TextField(verbose_name="内容")),
            ],
            options={
                "verbose_name_plural": "词牌名表",
            },
        ),
        migrations.CreateModel(
            name="ciauthor",
            fields=[
                (
                    "value",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="编号",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="作者")),
                ("long_desc", models.TextField(verbose_name="作者介绍")),
                ("short_desc", models.TextField(verbose_name="作者简介")),
            ],
            options={
                "verbose_name_plural": "作者表",
            },
        ),
        migrations.CreateModel(
            name="userinfo",
            fields=[
                (
                    "uid",
                    models.CharField(
                        default="",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="用户名",
                    ),
                ),
                ("password", models.CharField(max_length=8, verbose_name="密码")),
                ("email", models.CharField(max_length=20, verbose_name="邮箱")),
                ("age", models.IntegerField(default=18, verbose_name="年龄")),
            ],
            options={
                "verbose_name_plural": "用户信息表",
            },
        ),
    ]
